/*
 * Copyright (c) 2026 Martin Davis / locationtech.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v20.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 */
package org.locationtech.jts.algorithm.rocqref;

import org.locationtech.jts.algorithm.Orientation;
import org.locationtech.jts.geom.Coordinate;

import java.io.*;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.*;

/**
 * Loader and runner for proof vectors generated by the RocqRefRunner
 * (the extracted OCaml oracle from NetTopologySuite.Proofs).
 *
 * Used for differential testing / hardening of JTS orientation (and other)
 * against the machine-checked exact ORIENT_EXACT (full binary64, JTS #1106).
 *
 * Vectors are consumed from artifacts like:
 *   https://github.com/grootstebozewolf/NetTopologySuite.Proofs/actions/runs/26798343472/artifacts/7349017657
 *
 * Typical usage in RocqRefRunnerTest or adversarial:
 *   List<OrientCase> cases = RocqRefRunner.loadProofCases(
 *       "/org/locationtech/jts/algorithm/rocqref/orientation_proof_vectors.txt");
 *   RocqRefRunner.Result r = RocqRefRunner.run(cases);
 *   assertTrue(r.isSound());
 */
public class RocqRefRunner {

  public static class OrientCase {
    public final double p0x, p0y, p1x, p1y, qx, qy;
    public final int expectedSign; // -1,0,1 matching Orientation.index

    public OrientCase(double p0x, double p0y, double p1x, double p1y,
                      double qx, double qy, int expectedSign) {
      this.p0x = p0x; this.p0y = p0y;
      this.p1x = p1x; this.p1y = p1y;
      this.qx = qx; this.qy = qy;
      this.expectedSign = expectedSign;
    }

    /** JTS implementation under test. */
    public int jtsSign() {
      return Orientation.index(
          new Coordinate(p0x, p0y),
          new Coordinate(p1x, p1y),
          new Coordinate(qx, qy));
    }

    @Override
    public String toString() {
      return String.format("OrientCase(%.17g,%.17g ; %.17g,%.17g ; %.17g,%.17g) exp=%d",
          p0x,p0y, p1x,p1y, qx,qy, expectedSign);
    }
  }

  /**
   * Load cases from a classpath resource (the .txt vector file from proofs artifact).
   * Validates any claimed expectedSign in the file against a local exact (BD) computation.
   * Format: whitespace x0 y0 x1 y1 x2 y2 [expectedSign or POS/NEG/ZERO]
   */
  public static List<OrientCase> loadProofCases(String resourcePath) throws IOException {
    List<OrientCase> cases = new ArrayList<>();
    try (InputStream is = RocqRefRunner.class.getResourceAsStream(resourcePath)) {
      if (is == null) {
        throw new IOException("RocqRefRunner vector resource not found: " + resourcePath
            + " (did you copy from proofs artifact?)");
      }
      BufferedReader r = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8));
      String line;
      int lineNo = 0;
      while ((line = r.readLine()) != null) {
        lineNo++;
        String s = line.trim();
        if (s.isEmpty() || s.startsWith("#")) continue;
        String[] tok = s.split("\\s+");
        if (tok.length < 6) continue;
        double p0x = Double.parseDouble(tok[0]);
        double p0y = Double.parseDouble(tok[1]);
        double p1x = Double.parseDouble(tok[2]);
        double p1y = Double.parseDouble(tok[3]);
        double qx  = Double.parseDouble(tok[4]);
        double qy  = Double.parseDouble(tok[5]);
        int claimed = (tok.length >= 7) ? parseExpected(tok[6]) : 0;
        int derived = exactSignBD(p0x, p0y, p1x, p1y, qx, qy);
        if (tok.length >= 7 && claimed != derived) {
          throw new IllegalStateException("RocqRefRunner vector mismatch line " + lineNo
              + ": claimed=" + claimed + " derivedExact=" + derived + " for " + s);
        }
        cases.add(new OrientCase(p0x, p0y, p1x, p1y, qx, qy, derived));
      }
    }
    return cases;
  }

  private static int parseExpected(String t) {
    String u = t.toUpperCase();
    if (u.equals("POS") || u.equals("1") || u.equals("+1")) return 1;
    if (u.equals("NEG") || u.equals("-1")) return -1;
    if (u.equals("ZERO") || u.equals("0")) return 0;
    return Integer.parseInt(t);
  }

  /** Exact sign using BigDecimal (ground truth for the vector, and for hunter). */
  public static int exactSignBD(double p0x, double p0y, double p1x, double p1y, double qx, double qy) {
    BigDecimal x0 = bd(p0x), y0 = bd(p0y);
    BigDecimal x1 = bd(p1x), y1 = bd(p1y);
    BigDecimal x2 = bd(qx),  y2 = bd(qy);
    BigDecimal dx1 = x1.subtract(x0);
    BigDecimal dy1 = y1.subtract(y0);
    BigDecimal dx2 = x2.subtract(x0);
    BigDecimal dy2 = y2.subtract(y0);
    BigDecimal det = dx1.multiply(dy2).subtract(dy1.multiply(dx2));
    return det.signum();
  }

  private static BigDecimal bd(double d) {
    // Double.toString produces a decimal that roundtrips exactly to the binary64 value.
    return new BigDecimal(Double.toString(d));
  }

  /** Result of running a batch of cases. */
  public static class Result {
    public final int total;
    public final int mismatches;
    public Result(int total, int mismatches) {
      this.total = total;
      this.mismatches = mismatches;
    }
    public boolean isSound() { return mismatches == 0; }
    @Override public String toString() {
      return "RocqRefRunner.Result[total=" + total + " mismatches=" + mismatches + (isSound() ? " SOUND" : " UNSOUND") + "]";
    }
  }

  /** Execute the cases against current JTS impl, compare to expected from Rocq. */
  public static Result run(List<OrientCase> cases) {
    int bad = 0;
    for (OrientCase c : cases) {
      if (c.jtsSign() != c.expectedSign) bad++;
    }
    return new Result(cases.size(), bad);
  }

  /** Convenience: load + run + return result. */
  public static Result run(String resourcePath) throws IOException {
    return run(loadProofCases(resourcePath));
  }

  /** Simple hunter: generate N random (including extreme) cases, find JTS vs exact mismatches. */
  public static List<OrientCase> hunt(int n) {
    Random rnd = new Random(42); // reproducible
    List<OrientCase> bad = new ArrayList<>();
    double[] specials = {0, 1, -1, 1e20, 1e-20, Math.pow(2, 512), Math.pow(2, -540), 2.0*Math.pow(2,27), Math.pow(2,53)};
    for (int i = 0; i < n; i++) {
      double p0x = pick(rnd, specials);
      double p0y = pick(rnd, specials);
      double p1x = pick(rnd, specials);
      double p1y = pick(rnd, specials);
      double qx  = pick(rnd, specials);
      double qy  = pick(rnd, specials);
      int exp = exactSignBD(p0x,p0y,p1x,p1y,qx,qy);
      int jts = new OrientCase(p0x,p0y,p1x,p1y,qx,qy,exp).jtsSign();
      if (jts != exp) {
        bad.add(new OrientCase(p0x,p0y,p1x,p1y,qx,qy,exp));
        if (bad.size() > 10) break; // limit report
      }
    }
    return bad;
  }

  private static double pick(Random rnd, double[] specials) {
    if (rnd.nextDouble() < 0.3) return specials[rnd.nextInt(specials.length)];
    // random in various bins
    int exp = rnd.nextInt(1200) - 600; // wide
    double m = rnd.nextDouble() * 2 - 1;
    return m * Math.pow(2, exp);
  }
}
