/*
 * Copyright (c) 2026 grootstebozewolf
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v20.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 */
package org.locationtech.jts.geom.curved.adversarial;

import java.math.BigDecimal;
import java.math.MathContext;
import java.util.ArrayList;
import java.util.List;

import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.CoordinateSequence;
import org.locationtech.jts.geom.LineString;

/**
 * Reference runner for M-AREA-CP hardening, modeled on RocqRefRunner.
 * Computes "exact" (BigDecimal) signed area for a ring using the same
 * mathematical formula as CurvedArea, but without double rounding in the
 * intermediate steps (except the input doubles themselves are exact dyadics).
 *
 * Used to generate/validate vectors and hunt counterexamples (precision loss,
 * degen arcs, large coords, etc.) for the curve area implementation.
 *
 * To integrate with proofs: load vectors generated by oracle/driver.ml ARC_AREA
 * or from Rocq extractions (future).
 */
public final class CurveAreaRefRunner {

  private CurveAreaRefRunner() {}

  /** A reference case for a ring's signed area. */
  public static final class AreaCase {
    public final double[] coords; // interleaved x y ...
    public final BigDecimal expected; // exact ref signed area

    public AreaCase(double[] coords, BigDecimal expected) {
      this.coords = coords;
      this.expected = expected;
    }
  }

  public static final class Result {
    public long checked = 0;
    public long mismatches = 0;
    public final List<String> failures = new ArrayList<>();
    private static final int MAX = 20;

    void record(AreaCase c, double actual) {
      mismatches++;
      if (failures.size() < MAX) {
        failures.add("ring len=" + (c.coords.length/2) + " expected=" + c.expected + " but got " + actual);
      }
    }

    public boolean isSound() { return mismatches == 0; }

    public String toString() {
      StringBuilder sb = new StringBuilder();
      sb.append(checked).append(" cases, ").append(mismatches).append(" mismatches");
      for (String f : failures) sb.append("\n  ").append(f);
      return sb.toString();
    }
  }

  /** Exact ref signed area using BigDecimal port of the accumulate formula. */
  public static BigDecimal refSignedRingArea(double[] xy) {
    if (xy == null || xy.length < 6) return BigDecimal.ZERO;
    MathContext mc = MathContext.DECIMAL128;
    BigDecimal sum = BigDecimal.ZERO;
    int n = xy.length / 2;
    for (int i = 0; i + 1 < n; i++) {
      BigDecimal xs = new BigDecimal(xy[2*i], mc);
      BigDecimal ys = new BigDecimal(xy[2*i+1], mc);
      BigDecimal xe = new BigDecimal(xy[2*(i+1)], mc);
      BigDecimal ye = new BigDecimal(xy[2*(i+1)+1], mc);
      sum = sum.add( xs.multiply(ye, mc).subtract( xe.multiply(ys, mc), mc ) , mc);
    }
    // For full ring, close the last to first if not already? Assume closed input.
    // This is simplified; real impl would handle arcs too.
    // For this runner, we implement only straight for demo; arc contrib would use atan2 + Big.
    return sum.divide( new BigDecimal(2), mc );
  }

  /** Run JTS CurvedArea against cases, compare to ref. */
  public static Result run(List<AreaCase> cases) {
    Result r = new Result();
    for (AreaCase c : cases) {
      r.checked++;
      // Build temp ring
      Coordinate[] pts = new Coordinate[c.coords.length/2];
      for (int i=0; i<pts.length; i++) {
        pts[i] = new Coordinate(c.coords[2*i], c.coords[2*i+1]);
      }
      // Use JTS straight for now (to test the delegation fix)
      double actual = org.locationtech.jts.algorithm.Area.ofRing(pts);
      BigDecimal ref = c.expected;
      // Compare with tol for float nature
      double diff = Math.abs(actual - ref.doubleValue());
      if (diff > 1e-9) {
        r.record(c, actual);
      }
    }
    return r;
  }

  /**
   * Load area vectors from resources (e.g. generated by proofs oracle ARC_AREA
   * or Rocq). Format: space sep coords then expected (one ring per line).
   */
  public static List<AreaCase> loadVectors(java.io.InputStream in) throws java.io.IOException {
    List<AreaCase> out = new ArrayList<>();
    java.io.BufferedReader br = new java.io.BufferedReader(new java.io.InputStreamReader(in, java.nio.charset.StandardCharsets.UTF_8));
    String line;
    while ((line = br.readLine()) != null) {
      line = line.trim();
      if (line.isEmpty() || line.startsWith("#")) continue;
      String[] tok = line.split("\\s+");
      if (tok.length < 3) continue;
      double[] xy = new double[tok.length-1];
      for (int i=0; i<xy.length; i++) xy[i] = Double.parseDouble(tok[i]);
      BigDecimal exp = new BigDecimal(tok[tok.length-1]);
      out.add(new AreaCase(xy, exp));
    }
    return out;
  }

  /** Simple hunter: generate random rings, find where JTS != ref. */
  public static List<AreaCase> hunt(int n, long seed) {
    java.util.Random rnd = new java.util.Random(seed);
    List<AreaCase> bad = new ArrayList<>();
    for (int i=0; i<n; i++) {
      int m = 3 + rnd.nextInt(5);
      double[] xy = new double[2*m];
      for (int j=0; j<m; j++) {
        xy[2*j] = rnd.nextDouble() * 1e10 - 5e9; // large to stress precision
        xy[2*j+1] = rnd.nextDouble() * 1e10 - 5e9;
      }
      // close
      xy[2*(m-1)] = xy[0]; xy[2*(m-1)+1] = xy[1];
      BigDecimal ref = refSignedRingArea(xy);
      // simulate JTS straight
      Coordinate[] pts = new Coordinate[m];
      for (int k=0; k<m; k++) pts[k] = new Coordinate(xy[2*k], xy[2*k+1]);
      double jts = org.locationtech.jts.algorithm.Area.ofRing(pts);
      if (Math.abs(jts - ref.doubleValue()) > 1e-6) {
        bad.add(new AreaCase(xy, ref));
        if (bad.size() > 5) break;
      }
    }
    return bad;
  }
}
